CodaMais/CodaMais/urls.py
# Django.
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve
from django.conf.urls.i18n import i18n_patterns
# from django.template.response import TemplateResponse


# Local Django
from landing.views import home

urlpatterns = i18n_patterns(
    url('^user/', include('user.urls')),
    url('^exercise/', include('exercise.urls')),
    url('^forum/', include('forum.urls')),
    url('^theory/', include('theory.urls')),
    url(r'^$', home, name="landing_home"),
    url(r'^admin/', admin.site.urls),
    url(r'^about/', include('landing.urls')),
    # When using the Django's dev server, static files are served by default but
    # not media files, so you here we're force the server to consider them.
    url('^dashboard/', include('dashboard.urls')),
    url('^ranking/', include('ranking.urls')),
)

# When using the Django's dev server, static files are served by default but
# not media files, so you here we're force the server to consider them
if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT
        }),
        # url(r'^', TemplateResponse, {'template': '404.html'}),
    ]

CodaMais/user/urls.py
# Django.
from django.conf.urls import url

# Local Django.
from .views import (
    register_view,
    register_confirm,
    login_view,
    logout_view,
    edit_profile_view,
    profile_view,
    recover_password,
    recover_password_confirm,
)

urlpatterns = (
    # TODO(João) Change this url to landpage, and delete this url
    url(r'^register/', register_view, name='register_view'),

    url(r'^confirm/(?P<activation_key>\w+)/', register_confirm,
        name='confirm_account'),

    # TODO(João) Change this url to landpage, and delete this url
    url(r'^login/', login_view, name='login_view'),
    url(r'^logout/', logout_view, name='logout_view'),
    url(r'^edit/(?P<username>[\w|\W]+)/', edit_profile_view, name='edit'),
    url(r'^profile/(?P<username>[\w|\W]+)/', profile_view, name='profile_view'),

    # Recover password.
    url(r'^recoverpassword/', recover_password, name='recover_password'),
    url(r'^recover/(?P<activation_key>\w+)/', recover_password_confirm,
        name='recover_password_confirm'),
)

CodaMais/forum/forms.py
# Django.
from django import forms

# Local Django.
from forum.models import (
    Topic, Answer
)

from forum import constants
from django.utils.translation import ugettext_lazy as _


# Class: TopicForm
# The class represents all the fields of the topic in the site forum.
class TopicForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(
                                attrs={'class': 'form-control'}))

    subtitle = forms.CharField(widget=forms.TextInput(
                                    attrs={'class': 'form-control'}))

    description = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Topic
        exclude = ['author', 'date_topic', 'best_answer']

    def clean(self, *args, **kwargs):
        title = self.cleaned_data.get("title")
        subtitle = self.cleaned_data.get("subtitle")
        description = self.cleaned_data.get("description")

        if title is None:
            raise forms.ValidationError({'title': [_(constants.TITLE_SIZE)]})
        elif len(title) < constants.MIN_LENGTH_TITLE:
            raise forms.ValidationError({'title': [_(constants.TITLE_SIZE)]})
        elif len(title) > constants.MAX_LENGTH_TITLE:
            raise forms.ValidationError({'title': [_(constants.TITLE_SIZE)]})
        else:
            pass

        if subtitle is None:
            raise forms.ValidationError({'subtitle': [_(constants.SUBTITLE_SIZE)]})
        elif len(subtitle) < constants.MIN_LENGTH_SUBTITLE:
            raise forms.ValidationError({'subtitle': [_(constants.SUBTITLE_SIZE)]})
        elif len(subtitle) > constants.MAX_LENGTH_SUBTITLE:
            raise forms.ValidationError({'subtitle': [_(constants.SUBTITLE_SIZE)]})
        else:
            pass

        if description is None:
            raise forms.ValidationError({'description': [_(constants.TOPIC_DESCRIPTION_SIZE)]})
        elif len(description) < constants.MIN_LENGTH_TOPIC_DESCRIPTION:
            raise forms.ValidationError({'description': [_(constants.TOPIC_DESCRIPTION_SIZE)]})
        elif len(description) > constants.MAX_LENGTH_TOPIC_DESCRIPTION:
            raise forms.ValidationError({'description': [_(constants.TOPIC_DESCRIPTION_SIZE)]})
        else:
            pass

        return super(TopicForm, self).clean(*args, **kwargs)


class AnswerForm(forms.ModelForm):
    description = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Answer
        exclude = ['user', 'topic', 'date_answer']

CodaMais/templates/general/head.html
{% load static %}

<meta charset="utf-8" />
<link rel="icon" type="image/png" href="assets/img/favicon.ico">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

<title>Coda+</title>

<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
<meta name="viewport" content="width=device-width" />

<!-- Bootstrap core CSS     -->
<link rel="stylesheet" href="{% static "general/css/bootstrap.min.css" %}">

<!-- Animation library for notifications   -->
<link rel="stylesheet" href="{% static "general/css/animate.min.css" %}">

<!--  Light Bootstrap Table core CSS    -->
<link rel="stylesheet" href="{% static "general/css/light-bootstrap-dashboard.css" %}">

<!--  Personal CodaMais CSS    -->
<link rel="stylesheet" href="{% static "general/css/styles.css" %}">

<!--     Fonts and icons     -->
<link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
<link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="{% static "general/css/pe-icon-7-stroke.css" %}">

CodaMais/templates/general/javascript.html
<!-- {% load static %} -->

<!--   Core JS Files   -->
<!-- <script src="{% static "general/javascript/jquery-1.10.2.js" %}" type="text/javascript"></script>
<script src="{% static "general/javascript/bootstrap.min.js" %}" type="text/javascript"></script> -->

<!--  Checkbox, Radio & Switch Plugins -->
<!-- <script src="{% static "general/javascript/bootstrap-checkbox-radio-switch.js" %}" type="text/javascript"></script> -->

<!--  Charts Plugin -->
<!-- <script src="{% static "general/javascript/chartist.min.js" %}" type="text/javascript"></script> -->

<!--  Notifications Plugin    -->
<!-- <script src="{% static "general/javascript/bootstrap-notify.js" %}" type="text/javascript"></script> -->

<!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
<!-- <script src="{% static "general/javascript/light-bootstrap-dashboard.js" %}" type="text/javascript"></script> -->

<!-- Loading dashboard chart -->
<!-- <script src="{% static "general/javascript/dashboard.js" %}" type="text/javascript"></script> -->

<!-- {% block javascript %}{% endblock %} -->

<!-- <script type="text/javascript">
    $(document).ready(function(){

        $(".clickable-row").click(function() {
            window.location = $(this).data("href");
        });

        tinyMCE.init({
               selector:'#id_description',
               menubar:false,
        });

        $('#choose_best_answer').on('shown.bs.modal', function(event) {
            let url_best_answer = $(event.relatedTarget).data('url');
            $("#confirm_choose_best_answer").attr('href', url_best_answer);
        });

        $('#delete_confirmation_answer').on('shown.bs.modal', function(event) {
            let url_delete_answer = $(event.relatedTarget).data('url');
            $("#confirm_delete_answer").attr('href', url_delete_answer);
        });

        demo.initChartist();

    });
</script>  -->

CodaMais/templates/general/navigation_bar.html
{% load static %}

<nav class="navbar navbar-default navbar-fixed">
    <div class="container-fluid">
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-left">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-trophy"></i>
                  Ranking:  {{request.user.get_position}}º
                </a>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-bullseye"></i>
                  Pontuação:  {{ request.user.score }}
                </a>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-check-square"></i>
                  Exercício Corretos:  {{request.user.get_correct_exercises}}%
                </a>
              </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-user"></i>
                              {{ request.user.username }}
                            <b class="caret"></b>
                      </a>
                      <ul class="dropdown-menu">
                        <li><a href="{% url 'profile_view' request.user.username %}">Perfil</a></li>
                        <li><a href="{% url 'edit' request.user.username %}">Configurar Conta</a></li>
                      </ul>
                </li>
                <li>
                    <a href="{% url 'logout_view' %}">
                        Log out
                        <i class="fa fa-sign-out"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

CodaMais/templates/general/side_bar.html
{% load static %}

<div class="sidebar" data-color="black" data-image="{% static "general/images/sidebar-image.jpg" %}">

    <div class="sidebar-wrapper">
        <div class="logo">
            <a href="{% url 'dashboard' %}" class="simple-text">
              <img src="{% static "logo/logo.png" %}" width="140px" height="75px" align="center" ></img>
            </a>
        </div>

        <ul class="nav">
            <li class="{% if 'dashboard' in request.path %}active{% endif %}">
                <a href="{% url 'dashboard' %}">
                    <i class="pe-7s-home"></i>
                    <p>Dashboard</p>
                </a>
            </li>
            <li class="{% if 'theories' in request.path or 'theory' in request.path %}active{% endif %}">
                <a href="{% url 'theories' %}">
                    <i class="pe-7s-world"></i>
                    <p>Conteúdos</p>
                </a>
            </li>
            <li class="{% if 'exercises' in request.path or 'exercise' in request.path %}active{% endif %}">
                <a href="{% url 'list_exercises_not_deprecated' %}">
                    <i class="pe-7s-gym"></i>
                    <p>Exercícios</p>
                </a>
            </li>
            <li class="{% if 'topics' in request.path or 'topic' in request.path %}active{% endif %}">
                <a href="{% url 'list_all_topics' %}">
                    <i class="pe-7s-news-paper"></i>
                    <p>Fórum</p>
                </a>
            </li>
            <li class="{% if 'ranking' in request.path %}active{% endif %}">
                <a href="{% url 'show_ranking' %}">
                    <i class="pe-7s-cup"></i>
                    <p>Ranking</p>
                </a>
            </li>
            <li class="active-about">
                    <a href="{% url 'about' %}">
                        <i class="pe-7s-info"></i>
                        <p>Sobre</p>
                    </a>
            </li>
        </ul>
    </div>
</div>

CodaMais/templates/general/template.html
<!doctype html>
<html lang="en">

<head>
    {% csrf_token %}
    {% include "general/head.html" %}
</head>

<body>
    <div class="wrapper">
        {% include "general/side_bar.html" %}
        <div class="main-panel">
            {% include "general/navigation_bar.html" %}
            {% block title %} {% endblock %}
            <div class="content">
                <div class="container-fluid">
                    {% block content %} {% endblock %}
                </div>
            </div>
        </div>
    </div>
    {% block modal %} {% endblock %}
</body>

{% load static %}

<!--   Core JS Files   -->
<script src="{% static "general/javascript/jquery-1.10.2.js" %}" type="text/javascript"></script>
<script src="{% static "general/javascript/bootstrap.min.js" %}" type="text/javascript"></script>

<!--  Checkbox, Radio & Switch Plugins -->
<script src="{% static "general/javascript/bootstrap-checkbox-radio-switch.js" %}" type="text/javascript"></script>

<!--  Charts Plugin -->
<script src="{% static "general/javascript/chartist.min.js" %}" type="text/javascript"></script>

<!--  Notifications Plugin    -->
<script src="{% static "general/javascript/bootstrap-notify.js" %}" type="text/javascript"></script>

<!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
<script src="{% static "general/javascript/light-bootstrap-dashboard.js" %}" type="text/javascript"></script>

<!-- Loading dashboard chart -->
<script src="{% static "general/javascript/dashboard.js" %}" type="text/javascript"></script>

{% block javascript %}{% endblock %}

<script type="text/javascript">
    $(document).ready(function(){

        $(".clickable-row").click(function() {
            window.location = $(this).data("href");
        });

        tinyMCE.init({
               selector:'#id_description',
               menubar:false,
        });

        $('#choose_best_answer').on('shown.bs.modal', function(event) {
            let url_best_answer = $(event.relatedTarget).data('url');
            $("#confirm_choose_best_answer").attr('href', url_best_answer);
        });

        $('#delete_confirmation_answer').on('shown.bs.modal', function(event) {
            let url_delete_answer = $(event.relatedTarget).data('url');
            $("#confirm_delete_answer").attr('href', url_delete_answer);
        });

        demo.initChartist();

    });
</script>


</html>