CodaMais/CodaMais/urls.py
# Django.
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve
from django.conf.urls.i18n import i18n_patterns
# from django.template.response import TemplateResponse


# Local Django
from landing.views import home

urlpatterns = i18n_patterns(
    url('^user/', include('user.urls')),
    url('^exercise/', include('exercise.urls')),
    url('^forum/', include('forum.urls')),
    url('^theory/', include('theory.urls')),
    url(r'^$', home, name="landing_home"),
    url(r'^admin/', admin.site.urls),
    url(r'^about/', include('landing.urls')),
    # When using the Django's dev server, static files are served by default but
    # not media files, so you here we're force the server to consider them.
    url('^dashboard/', include('dashboard.urls')),
    url('^ranking/', include('ranking.urls')),
)

# When using the Django's dev server, static files are served by default but
# not media files, so you here we're force the server to consider them
if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT
        }),
        # url(r'^', TemplateResponse, {'template': '404.html'}),
    ]

CodaMais/dashboard/urls.py
# Django.
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

# Local Django.
from dashboard.views import dashboard, user_exercise_chart

urlpatterns = (
    url(r'^dashboard/', login_required(dashboard), name='dashboard'),
    url(r'^userExerciseChart', user_exercise_chart, name='user_exercise_chart'),
)

CodaMais/user/urls.py
# Django.
from django.conf.urls import url

# Local Django.
from .views import (
    register_view,
    register_confirm,
    login_view,
    logout_view,
    edit_profile_view,
    profile_view,
    recover_password,
    recover_password_confirm,
)

urlpatterns = (
    # TODO(João) Change this url to landpage, and delete this url
    url(r'^register/', register_view, name='register_view'),

    url(r'^confirm/(?P<activation_key>\w+)/', register_confirm,
        name='confirm_account'),

    # TODO(João) Change this url to landpage, and delete this url
    url(r'^login/', login_view, name='login_view'),
    url(r'^logout/', logout_view, name='logout_view'),
    url(r'^edit/(?P<username>[\w|\W]+)/', edit_profile_view, name='edit'),
    url(r'^profile/(?P<username>[\w|\W]+)/', profile_view, name='profile_view'),

    # Recover password.
    url(r'^recoverpassword/', recover_password, name='recover_password'),
    url(r'^recover/(?P<activation_key>\w+)/', recover_password_confirm,
        name='recover_password_confirm'),
)

CodaMais/dashboard/models.py
from django.db import models

# Create your models here.

CodaMais/forum/models.py
'''
    Copyright (C) 2017, CodaMais.
    License: GNU General Public License v3.0, see LICENSE.txt
    App: forum
    File: models.py
    Contains all classes related to the forum, it is django's default to keep all models in single file.
'''

# Django.
from django.db import models

# local Django.
from forum import constants
from user.models import User


# Class: Topic
# The class represents a topic in the site forum.
class Topic(models.Model):
    title = models.CharField(max_length=constants.MAX_LENGTH_TITLE)
    subtitle = models.CharField(max_length=constants.MAX_LENGTH_SUBTITLE)
    author = models.ForeignKey(
          User,
          on_delete=models.CASCADE,)
    description = models.CharField(max_length=constants.MAX_LENGTH_TOPIC_DESCRIPTION)
    date_topic = models.DateTimeField(auto_now_add=True, blank=True)
    best_answer = models.ForeignKey('Answer', models.SET_NULL, related_name='best_answer', null=True)
    locked = models.BooleanField(default=False)

    def new_topics():
        topics = Topic.objects.all().order_by('-id')[:5]
        return topics

    def answers(self):
        assert self is not None, "Topic not exists."
        # Getting all current topic answers except the best answer
        answers = Answer.objects.filter(topic=self)
        return answers

    def __str__(self):
        return self.title


# Class: Answer
# The class represents a answer to a topic in the site forum.
class Answer(models.Model):
    description = models.CharField(max_length=constants.MAX_LENGTH_ANSWER_DESCRIPTION)
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,)
    topic = models.ForeignKey(
        Topic,
        on_delete=models.CASCADE,)
    date_answer = models.DateTimeField(auto_now_add=True, blank=True)

    def creates_answer(self, user, topic, description):
        self.user = user
        self.topic = topic
        self.description = description
        self.save()

    def __str__(self):
        return self.description

CodaMais/dashboard/views.py
import logging

from datetime import timedelta

from django.shortcuts import render, render_to_response
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.template import RequestContext

from django.http import JsonResponse

from forum.models import Topic
from exercise.models import Exercise, UserExerciseSubmission
from ranking.views import get_users_with_bigger_score
from exercise.views import get_user_exercises_last_submissions
from . import constants

logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger(constants.DEFAULT_LOGGER)


@login_required()
def dashboard(request):
    user = request.user

    ranking_data = get_users_with_bigger_score()

    # getting the last 5 topics created
    new_topics_data = Topic.new_topics()

    # getting the last 5 exercises created
    new_exercises_data = Exercise.new_exercises()
    user_last_exercises = get_user_exercises_last_submissions(user)

    return render(request, 'dashboard.html', {
        'data': ranking_data,
        'topics': new_topics_data,
        'exercises': new_exercises_data,
        'user_exercises': user_last_exercises
    })


def user_exercise_chart(request):
    user = request.user
    days_ago = constants.CHART_USER_EXERCISES_SUBMISSIONS_DAYS
    # calculates the date given the number of days ago
    days_ago_date = timezone.now().date() - timedelta(days=days_ago)

    # get the user exercises submissions
    user_exercises_submissions = UserExerciseSubmission.submissions_by_day(
        user,
        days_ago_date
    )

    # Lists that corresposd to fields in chart.
    label_date_field = []
    series_correct_answer = []
    series_number_submissions = []

    for user_exercise_submission in user_exercises_submissions:
        logger.info(user_exercise_submission)
        submission_date = user_exercise_submission['date_submission']

        # Feed the lists of exercises submissions (days, corrects, submissions)
        label_date_field.append(str(submission_date.day) + '/' + str(submission_date.month))
        series_correct_answer.append(int(user_exercise_submission['corrects']))
        series_number_submissions.append(user_exercise_submission['submissions'])

    # Creates the JSON structure of the chart
    data = {
        'labels': label_date_field,
        'series': [
            series_correct_answer,
            series_number_submissions
        ]
    }

    return JsonResponse(data)


# This method is called when the aplication raises a 404 error and replace the debug
# 404 error default page for a customized one (404.html).
def handler404(request):
    response = render_to_response('404.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 404
    return response

CodaMais/dashboard/templates/dashboard.html
{% extends "general/template.html" %}

{% block content %}

<div class="row">

    <div class="col-md-4">
        <div class="card">
            <div class="header">
                <h4 class="title">Top 5 - Ranking</h4>
                <p class="category">Lista Dinâmica estilo Tabela</p>
            </div>
            <div class="content table-responsive table-full-width">
                <table class="table table-hover table-striped">
                    <thead>
                        <th align = 'center'>Username</th>
                        <th align = 'center'>Pontuação</th>
                        <th align = 'center'>Nº Exer</th>
                    </thead>
                    <tbody>
                        {% for user, completed_exercises in data %}
                        <tr align = 'left' class='clickable-row'  data-href="{% url 'profile_view' user.username %}">
                            <td>{{user.username}}</td>
                            <td align = 'center'>{{user.score}}</td>
                            <td align = 'center'>{{completed_exercises}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="content">
              <div class="footer">
                  <hr>
                  <div class="stats">
                      <i class="fa fa-history"></i> Ranking ordenado pela score
                  </div>
              </div>
            </div>
        </div>
    </div>


    <div class="col-md-8">
        <div class="card">
            <div class="header">
                <h4 class="title">Quantidade de Exercícios Concluídos por Dia</h4>
                <p class="category">Gráfico Dinâmico</p>
            </div>
            <div class="content">
                <!-- Content Structure -->
                <div id="exercisesMadeByUser" class="ct-chart ct-perfect-fourth ct-series-a"></div>
                <div class="footer">
                    <div class="legend">
                        <i class="fa fa-circle text-info"></i> Exercícios Certos
                        <i class="fa fa-circle text-danger"></i> Número de Tentativas
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>


<div class="row">
    <div class="col-md-4">
        <div class="card ">
            <div class="header">
                <h4 class="title">Últimas submissões</h4>
            </div>
            <div class="content table-responsive table-full-width">
                <table class="table table-hover table-striped">
                    <thead>
                        <th align = 'center'>Título</th>
                        <th align = 'center'>Status</th>
                        <th align = 'center'>Score</th>
                    </thead>
                    <tbody>
                        {% for submission in user_exercises %}
                        <tr class='clickable-row'  data-href="{% url 'show_exercise' submission.exercise.id %}">
                          <td id=column>
                            {{submission.exercise.title|truncatechars:40}}
                          </td>
                          <td id=align>
                              {% if submission.status == True %}
                                <i class="fa fa-check text-success"></i>
                              {% elif submission.status == False and submission.number_submission %}
                                <i class="fa fa-times text-danger"></i>
                              {% else %}
                                <!-- Nothing to do -->
                              {% endif %}
                          </td>
                          <td>{{submission.exercise.score}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card ">
            <div class="header">
                <h4 class="title">Novos Exercícios</h4>
            </div>
            <div class="content table-responsive table-full-width">
                <table class="table table-hover table-striped">
                    <thead>
                        <th align = 'center'>Título</th>
                        <th align = 'center'>Score</th>
                    </thead>
                    <tbody>
                        {% for exercise in exercises %}
                        <tr class='clickable-row'  data-href="{% url 'show_exercise' exercise.id %}">
                          <td>{{exercise.title}}</td>
                          <td>{{exercise.score}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card ">
            <div class="header">
                <h4 class="title">Novos Tópicos no Fórum</h4>
            </div>
            <div class="content table-responsive table-full-width">
                <table class="table table-hover table-striped">
                    <thead>
                        <th>Título</th>
                        <th class="text-right">Respostas</th>
                    </thead>
                    <tbody>
                        {% for topic in topics %}
                        <tr class='clickable-row'  data-href="{% url 'show_topic' topic.id %}">
                          <td>{{topic.title}}</td>
                          <td class="text-right">{{topic.answer_set.all|length}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>

{% endblock %}